# Generated by Django 5.1.5 on 2025-01-31 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=100)),
                ('country_name', models.CharField(max_length=100)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('temperature', models.FloatField()),
                ('wind_speed', models.FloatField()),
                ('cloud_cover', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('temp_color', models.CharField(blank=True, max_length=7)),
                ('wind_color', models.CharField(blank=True, max_length=7)),
                ('cloud_color', models.CharField(blank=True, max_length=7)),
            ],
        ),
    ]
